version: "3.8"

services:
  db:
    container_name: shieldchat_db
    image: postgres:13.1
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: shieldchat

  app:
    container_name: shieldchat_backend
    build: .
    ports:
      - 3333:3333
    volumes:
      - ./:/usr/app
    depends_on:
      - db
